
#Tier Config. This config is synced from server to client.
[tier]

	#Energy Cubes
	[tier.energy_cubes]
		#Maximum number of Joules Basic energy cubes can store.
		basicStorage = "40000000"
		#Output rate in Joules of Basic energy cubes.
		basicOutput = "40000"
		#Maximum number of Joules Advanced energy cubes can store.
		advancedStorage = "160000000"
		#Output rate in Joules of Advanced energy cubes.
		advancedOutput = "160000"
		#Maximum number of Joules Elite energy cubes can store.
		eliteStorage = "640000000"
		#Output rate in Joules of Elite energy cubes.
		eliteOutput = "640000"
		#Maximum number of Joules Ultimate energy cubes can store.
		ultimateStorage = "2560000000"
		#Output rate in Joules of Ultimate energy cubes.
		ultimateOutput = "2560000"
		#Maximum number of Joules Creative energy cubes can store.
		creativeStorage = "18446744073709551615.9999"
		#Output rate in Joules of Creative energy cubes.
		creativeOutput = "18446744073709551615.9999"

	#Fluid Tanks
	[tier.fluid_tanks]
		#Storage size of Basic fluid tanks in mB.
		#Range: > 1
		basicStorage = 140000
		#Output rate of Basic fluid tanks in mB.
		#Range: > 1
		basicOutput = 4000
		#Storage size of Advanced fluid tanks in mB.
		#Range: > 1
		advancedStorage = 280000
		#Output rate of Advanced fluid tanks in mB.
		#Range: > 1
		advancedOutput = 8000
		#Storage size of Elite fluid tanks in mB.
		#Range: > 1
		eliteStorage = 560000
		#Output rate of Elite fluid tanks in mB.
		#Range: > 1
		eliteOutput = 16000
		#Storage size of Ultimate fluid tanks in mB.
		#Range: > 1
		ultimateStorage = 1120000
		#Output rate of Ultimate fluid tanks in mB.
		#Range: > 1
		ultimateOutput = 32000
		#Storage size of Creative fluid tanks in mB.
		#Range: > 1
		creativeStorage = 2147483647
		#Output rate of Creative fluid tanks in mB.
		#Range: > 1
		creativeOutput = 1073741823

	#Chemical Tanks
	[tier.chemical_tanks]
		#Storage size of Basic chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		basicStorage = 640000
		#Output rate of Basic chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		basicOutput = 2560
		#Storage size of Advanced chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		advancedStorage = 1280000
		#Output rate of Advanced chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		advancedOutput = 5120
		#Storage size of Elite chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		eliteStorage = 2560000
		#Output rate of Elite chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		eliteOutput = 10280
		#Storage size of Ultimate chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		ultimateStorage = 5120000
		#Output rate of Ultimate chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		ultimateOutput = 20560
		#Storage size of Creative chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		creativeStorage = 9223372036854775807
		#Output rate of Creative chemical tanks in mB.
		#Range: 1 ~ 9223372036854775807
		creativeOutput = 4611686018427387903

	#Bins
	[tier.bins]
		#The number of items Basic bins can store.
		#Range: > 1
		basicStorage = 40960
		#The number of items Advanced bins can store.
		#Range: > 1
		advancedStorage = 81920
		#The number of items Elite bins can store.
		#Range: > 1
		eliteStorage = 327680
		#The number of items Ultimate bins can store.
		#Range: > 1
		ultimateStorage = 2621440
		#The number of items Creative bins can store.
		#Range: > 1
		creativeStorage = 2147483647

	#Induction
	[tier.induction]
		#Maximum number of Joules Basic induction cells can store.
		basicStorage = "80000000000"
		#Maximum number of Joules Advanced induction cells can store.
		advancedStorage = "640000000000"
		#Maximum number of Joules Elite induction cells can store.
		eliteStorage = "5120000000000"
		#Maximum number of Joules Ultimate induction cells can store.
		ultimateStorage = "40000000000000"
		#Maximum number of Joules Basic induction providers can output or accept.
		basicOutput = "2560000"
		#Maximum number of Joules Advanced induction providers can output or accept.
		advancedOutput = "20480000"
		#Maximum number of Joules Elite induction providers can output or accept.
		eliteOutput = "163840000"
		#Maximum number of Joules Ultimate induction providers can output or accept.
		ultimateOutput = "1310720000"

	#Transmitters
	[tier.transmitters]

		#Universal Cables
		[tier.transmitters.energy]
			#Internal buffer in Joules of each Basic universal cable.
			basicCapacity = "80000"
			#Internal buffer in Joules of each Advanced universal cable.
			advancedCapacity = "1280000"
			#Internal buffer in Joules of each Elite universal cable.
			eliteCapacity = "10240000"
			#Internal buffer in Joules of each Ultimate universal cable.
			ultimateCapacity = "81920000000000"

		#Mechanical Pipes
		[tier.transmitters.fluid]
			#Capacity of Basic mechanical pipes in mB.
			#Range: > 1
			basicCapacity = 40000
			#Pump rate of Basic mechanical pipes in mB/t.
			#Range: > 1
			basicPullAmount = 5120
			#Capacity of Advanced mechanical pipes in mB.
			#Range: > 1
			advancedCapacity = 80000
			#Pump rate of Advanced mechanical pipes in mB/t.
			#Range: > 1
			advancedPullAmount = 10000
			#Capacity of Elite mechanical pipes in mB.
			#Range: > 1
			eliteCapacity = 640000
			#Pump rate of Elite mechanical pipes in mB/t.
			#Range: > 1
			elitePullAmount = 160000
			#Capacity of Ultimate mechanical pipes in mB.
			#Range: > 1
			ultimateCapacity = 5120000
			#Pump rate of Ultimate mechanical pipes in mB/t.
			#Range: > 1
			ultimatePullAmount = 640000

		#Pressurized Tubes
		[tier.transmitters.gas]
			#Capacity of Basic pressurized tubes in mB.
			#Range: 1 ~ 9223372036854775807
			basicCapacity = 80000
			#Pump rate of Basic pressurized tubes in mB/t.
			#Range: 1 ~ 9223372036854775807
			basicPullAmount = 10000
			#Capacity of Advanced pressurized tubes in mB.
			#Range: 1 ~ 9223372036854775807
			advancedCapacity = 640000
			#Pump rate of Advanced pressurized tubes in mB/t.
			#Range: 1 ~ 9223372036854775807
			advancedPullAmount = 40000
			#Capacity of Elite pressurized tubes in mB.
			#Range: 1 ~ 9223372036854775807
			eliteCapacity = 10000000
			#Pump rate of Elite pressurized tubes in mB/t.
			#Range: 1 ~ 9223372036854775807
			elitePullAmount = 1280000
			#Capacity of Ultimate pressurized tubes in mB.
			#Range: 1 ~ 9223372036854775807
			ultimateCapacity = 160000000
			#Pump rate of Ultimate pressurized tubes in mB/t.
			#Range: 1 ~ 9223372036854775807
			ultimatePullAmount = 10240000

		#Logistical Transporters
		[tier.transmitters.items]
			#Item throughput rate of Basic logistical transporters in items/half second.
			#Range: > 1
			basicPullAmount = 10
			#Five times travel speed of Basic logistical transporter.
			#Range: > 1
			basicSpeed = 50
			#Item throughput rate of Advanced logistical transporters in items/half second.
			#Range: > 1
			advancedPullAmount = 160
			#Five times travel speed of Advanced logistical transporter.
			#Range: > 1
			advancedSpeed = 100
			#Item throughput rate of Elite logistical transporters in items/half second.
			#Range: > 1
			elitePullAmount = 320
			#Five times travel speed of Elite logistical transporter.
			#Range: > 1
			eliteSpeed = 200
			#Item throughput rate of Ultimate logistical transporters in items/half second.
			#Range: > 1
			ultimatePullAmount = 640
			#Five times travel speed of Ultimate logistical transporter.
			#Range: > 1
			ultimateSpeed = 500

		#Thermodynamic Conductors
		[tier.transmitters.heat]
			#Conduction value of Basic thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			basicInverseConduction = 5.0
			#Heat capacity of Basic thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			basicHeatCapacity = 1.0
			#Insulation value of Basic thermodynamic conductor.
			#Range: 0.0 ~ 1.7976931348623157E308
			basicInsulation = 10.0
			#Conduction value of Advanced thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			advancedInverseConduction = 5.0
			#Heat capacity of Advanced thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			advancedHeatCapacity = 1.0
			#Insulation value of Advanced thermodynamic conductor.
			#Range: 0.0 ~ 1.7976931348623157E308
			advancedInsulation = 400.0
			#Conduction value of Elite thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			eliteInverseConduction = 5.0
			#Heat capacity of Elite thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			eliteHeatCapacity = 1.0
			#Insulation value of Elite thermodynamic conductor.
			#Range: 0.0 ~ 1.7976931348623157E308
			eliteInsulation = 8000.0
			#Conduction value of Ultimate thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			ultimateInverseConduction = 5.0
			#Heat capacity of Ultimate thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			ultimateHeatCapacity = 1.0
			#Insulation value of Ultimate thermodynamic conductor.
			#Range: 0.0 ~ 1.7976931348623157E308
			ultimateInsulation = 100000.0

